### ISSUE TITLE
Not seeing autocompletion 

### ISSUE THREAD

**Issue by hnry** [Cynddl/sublime-text-merlin#12]
I am not seeing the autocompletion but I am seeing highlighted white warnings for Core library definitions if I don't use a `.merlin` file. 

<img width="599" alt="screen shot 2016-02-27 at 3 24 52 pm" src="https://cloud.githubusercontent.com/assets/25837/13375149/4812c834-dd66-11e5-9ccf-c52f7e40f896.png">

When I add `PKG core` to my `.merlin` file the highlighting goes away. So I assume it's working in that area. But still no autocompletion.

I do see autocompletion and snippets for builtin keywords for OCaml but it's kind of _poor_ so I assume it's part of Sublime's standard package for OCaml and not this plugin working there either?

Also I am not seeing any type information in the status bar or warnings there either. Not sure if I am suppose to... But otherwise not much happens with this plugin versus without it except for the highlighting white borders for unknown functions.

What am I doing wrong?

**Comment by cynddl** [comment]
Hi @hnry,

Can you share which OS you use, and the versions of sublime text, sublime-text-merlin, and merlin on your system?

Thanks!

**Comment by hnry** [comment]
```
$ opam show merlin
             package: merlin
             version: 2.3.1
   installed-version: 2.3.1 [4.02.3]
```

OS X 10.11.3
Sublime 3103

sublime-text-merlin is whatever the latest is from package control , not sure how to check. But I installed it last night, and re-installed just moments ago.

Update >
For what it's worth I am able to get autocompletion working in atom, but I did have to set ocamlmerlin path. So I think my merlin setup is ok.
I also did try setting this path in sublime-text-merlin too and without.

**Comment by hnry** [comment]
Installed Fedora 23 VM to try this out. I'm also not seeing autocompletions on there either. 
Sublime 3103, also tried out Sublime 2 2221
merlin 2.3.1 [4.02.1]

In all 3 situations (OS X, Sublime 3103) (Fedora23 Sublime 3103) (Fedora23 Sublime 2221) I can not get autocompletion to work. They all report warning / syntax error highlighting for unknown symbols. They all correctly show errors when I don't have core pulled in by merlin (like the picture in the original post), and then remove the errors when I do have it pulled in. They all will show ocamlmerlin running in the background correctly.

Except in Fedora23 (Sublime 2 or 3) the jump to definition seems to work correctly. This does not work on OS X for me, it says it can't find the ML files.

But like I said no autocompletion in all 3 scenarios...
And as noted previously I am able to get autocompletion working in atom just fine on my OS X system. (So I can't imagine it being an issue with my merlin install.)

**Comment by hnry** [comment]
Ok the problem is with whatever is on Package Control, when I clone this repo for install, it works. 
https://packagecontrol.io/packages/Merlin This page also states the last modification was over a year ago, but this repository has more recent commits. So really this is just a simple issue of out dated package on package control :(

Side note:
This does not feel right?
If I type "whi" `while` does not show up.
If I type "whil" `while` shows, but not if I start over the 2 "with_*" functions are gone?

Why is it not showing all 3 if it matches? Why is it exclusive, it's either one or the other? And why does the behaviour change depending on last look up?
IE:
"whi" does not show `while`. I type "whil", now it shows `while`.
I restart, type "whi". I expect it to not show `while` like the first try, but it does this time! But now it leaves off the 2 "with_*" functions.

![autocomplete](https://cloud.githubusercontent.com/assets/25837/13454345/7a7d64c6-e024-11e5-836d-bb7df269a730.gif)

**Comment by cynddl** [comment]
Alright, I finally updated the plugin on Package Control. It should be available soon! 

As for the autocompletion (`while` not showing up), it seems like it is the standard behavior of _merlin_. Indeed, `Lis` shows `List` but `whi` does not show `while`.

**Comment by let-def** [comment]
Merlin only report semantics information, not concrete syntax. So `while` is never reported by merlin.

It seems to be a sublime-text behavior to fall back to another completion source in absence of results. As for the results staying after you erased characters, this is again a sublime-text behavior (I would hazard a guess that it is over optimistic caching).
