### ISSUE TITLE
Labeled argument ~f and type checking error

### ISSUE THREAD

**Issue by gajaka** [Cynddl/sublime-text-merlin#13]
Hi guys,
There is an error I noticed ( static type checking ). Perhaps it is up to me but it passed successfully in UTop. Please take look at attached files.
Regards
Dragan
![error1](https://cloud.githubusercontent.com/assets/3278250/15775679/255f239e-297b-11e6-977a-1242f063e942.jpg)
![utop1](https://cloud.githubusercontent.com/assets/3278250/15775680/25600782-297b-11e6-9bdd-cf88a1e9887d.jpg)

**Comment by cynddl** [comment]
Hi Dragan,

It seems like an issue with OCaml/Merlin and not the Sublime Text plugin. You try to use `List.exists` with labels. I assume you used `Core.Std` in utop and not in Sublime Text:

``` ocaml
(* Works *)
open Core.Std;;

let func = function el -> true in
List.exists [] ~f:func;;
```

``` ocaml
(* Fail *)
let func = function el -> true in
List.exists [] ~f:func;;
```

In the future, please insert source code directly (without images). It's easier to copy code.

**Comment by gajaka** [comment]
Thanks for your answer ( yes you are right I used Core.Std in utop and not in SublimeText ).
Sure in the future I will paste code example.
