### ISSUE TITLE
Merlin from Package Control is out of date

### ISSUE THREAD

**Issue by nopjmp** [Cynddl/sublime-text-merlin#17]
Merlin returns "invalid arguments" when installed from Package Control. Using git, I have no issues.

**Comment by cynddl** [comment]
Yes indeed. It's still on version 0.3.4 on Package Control. It seems like the tag ``0.4`` is not recognized, I'll try with ``0.4.0``. Thanks!

**Comment by nopjmp** [comment]
I wonder if it's because it's a "prerelease" on Github.

**Comment by cynddl** [comment]
Fixed on https://packagecontrol.io/packages/Merlin!
