### ISSUE TITLE
Interested in Reason support?

### ISSUE THREAD

**Issue by chenglou** [Cynddl/sublime-text-merlin#18]
Hey @cynddl, I was wondering if you'd be interested in supporting [Reason](http://facebook.github.io/reason/) in your plugin? We currently have a barebone plugin [here](https://github.com/facebook/reason/tree/master/editorSupport/sublime-reason), but it'd be nice to unite the effort.

**Comment by let-def** [comment]
I am hijacking the thread a bit. Merlin protocol changed a lot in development version. There is backward compatible mode, but which doesn't give access to new features.

So while it should work out of the box on most setups, it would be nice to port editor modes (I plan to take a look at sublime-text-merlin, but some help is welcome too :)).

**Comment by cynddl** [comment]
Hi @chenglou, it would be nice to support Reason also. However, it seems like the parsing is done by *refmt* and I'm a little worried to have a single package for two different languages and two different ways of parsing (*refmt* using *merlin* & *merlin* directly). I assume that _refmt_ cannot process OCaml code?

@let-def Could you point me to a list of the recent changes? Thanks!

**Comment by let-def** [comment]
@cynddl: you can see a WIP documentation here: https://github.com/ocaml/merlin/blob/master/doc/dev/PROTOCOL.md . I will provide you with patches asap.

**Comment by chenglou** [comment]
@cynddl merlin has first-class support for reason; as long as it's vision 2.5.1+ and the user has the relevant reason binaries (refmt. ocamlmerlin-reason) available in $PATH everything should just work.

**Comment by sgrove** [comment]
Sorry to bump, but we have a team member that's loathe to leave Sublime and needs to work on our Reason project. It'd be great to have a smooth merlin integration!

**Comment by let-def** [comment]
Just enabling Merlin on reason file should be enough to provide minimal support: in `helpers.py`, `is_ocaml` should returns true on reason files.

**Comment by chenglou** [comment]
Closing this, as [sublime-reason](https://github.com/reasonml-editor/sublime-reason) now uses [LSP](https://github.com/tomv564/LSP) and also supports ocaml.

@let-def one less editor you need to test merlin on!
