### ISSUE TITLE
Small tutorial  for non merlin/vim users

### ISSUE THREAD

**Issue by modlfo** [Cynddl/sublime-text-merlin#3]
It would be great having a small getting started guide for users like me that are not familiar with merlin or vim.

**Comment by cynddl** [comment]
Hmm, this repository is only a plugin for Sublime Text. If you want a guide for merlin and vim, you should probably check on merlin's repo: https://github.com/the-lambda-church/merlin.

**Comment by modlfo** [comment]
Sorry I didn't explained myself. 

I have installed your plugin but I have no idea how to use it (shortcuts, available commands,etc).

**Comment by let-def** [comment]
The first version of merlin was not easy to bind to sublime-text. The next branch of merlin (merlin2 on https://github.com/the-lambda-church/merlin) solves this issue.

I started porting the sublime-text mode, see http://github.com/def-lkb/sublime-text-merlin
This really needs some testers, I can help you setup an install.

Also, if you know sublime-text, improving the integration would be nice too.

**Comment by modlfo** [comment]
@def-lkb  I have installed your port and I have started using it. I haven't figured out all the features of merlin but so far works fine.

Thanks

**Comment by cynddl** [comment]
Closing this issue since it's not directly related to this project.
